apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-migrate-to-postgres
  namespace: caloriechecker-prod
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: django-migrate
    ports:
    - protocol: TCP
      port: 5432