server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    default_type application/octet-stream;

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}