apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: caloriechecker-prod

  labels:
    app: frontend
    tier: frontend
    environment: production

  annotations:
    description: "React/Vite SPA served by Nginx for CalorieChecker frontend"
    version: "1.0.0"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        environment: production

    spec:
      terminationGracePeriodSeconds: 15
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: frontend
                topologyKey: kubernetes.io/hostname

      containers:
        - name: frontend
          image: vnikiforovski0604/caloriechecker-frontend:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 200m
              memory: 256Mi

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 3"]

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          startupProbe:
            httpGet:
              path: /
              port: 80

            failureThreshold: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 20
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3