apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: frontend-pdb
  namespace: caloriechecker-prod

  labels:
    app: frontend
    tier: frontend

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: frontend