apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: caloriechecker-prod

  labels:
    app: frontend
    tier: frontend

  annotations:
    description: "Internal ClusterIP service for React frontend served by Nginx. External access via Ingress at path '/'."

spec:
  type: ClusterIP

  selector:
    app: frontend

  ports:
    - name: http
      protocol: TCP
      port: 80

      targetPort: 80